name: Continuous Integration
 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    
 
jobs:
  automation-test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18, 20 ]
 
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install --force
          npm run ci:test