name: Continuous Integration
 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    
 
jobs:
  automation-test-job:
    runs-on: ubuntu-latest
    env:
      RUNNER_TOOL_CACHE: /toolcache
    strategy:
      matrix:
        node: [ 18, 20 ]
 
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
          run_install: false
          standalone: true
          dest: ~/setup-pnpm
      - name: npm install and test
        run: |
          pnpm install --force --frozen-lockfile --silent
          pnpm run test
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run build
          start: pnpm start
          browser: edge
          config: pageLoadTimeout=100000,baseUrl=http://localhost:3000
      - name: Save video
        uses: actions/upload-artifact@v2
        with:
          name: sample_spec.js.mp4
          path: cypress/videos/sample_spec.js.mp4
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Cypress Tests
          path: cypress/results/results.xml
          reporter: java-junit
          fail-on-error: true
      - name: e2e test
        run: |
          pnpm run ci:test