name: Continuous Integration
 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    
 
jobs:
  automation-test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]
 
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
          run_install: false
          standalone: true
          dest: ~/setup-pnpm
      - name: npm install and test
        run: |
          pnpm install --force
          pnpm run ci:test